-- Migration: Cleanup Example Data for Bank Notes
-- Date: 2026-03-03
-- Description: Removes example "Gastos Bancarios", "Impuestos", and "Comisiones" 
-- documents from Finanzas that were not generated by the banking module.

BEGIN;

-- 1. Identify and delete applications of payment for example documents
DELETE FROM public.aplicaciones_pago
WHERE comprobante_id IN (
    SELECT id FROM public.comprobantes
    WHERE (tipo IN ('ncb_bancaria', 'ndb_bancaria') OR razon_social_socio = 'Gastos Varios / Otros')
    AND metadata->>'transaccion_id' IS NULL
);

-- 2. Delete instruments of payment associated with those movements
DELETE FROM public.instrumentos_pago
WHERE movimiento_id IN (
    SELECT id FROM public.movimientos_tesoreria
    WHERE (clase_documento IN ('NCB', 'NDB') OR categoria IN ('Gastos Bancarios', 'Impuestos y Tasas', 'Comisiones Bancarias'))
    AND metadata->>'transaccion_id' IS NULL
);

-- 3. Delete the movements themselves
DELETE FROM public.movimientos_tesoreria
WHERE (clase_documento IN ('NCB', 'NDB') OR categoria IN ('Gastos Bancarios', 'Impuestos y Tasas', 'Comisiones Bancarias'))
AND metadata->>'transaccion_id' IS NULL;

-- 4. Finally delete the vouchers (comprobantes)
DELETE FROM public.comprobantes
WHERE (tipo IN ('ncb_bancaria', 'ndb_bancaria') OR razon_social_socio = 'Gastos Varios / Otros')
AND metadata->>'transaccion_id' IS NULL;

COMMIT;
